/**
 * TermsScreen - Terms and Conditions for AskToddy
 */

import React from 'react';
import { View, Text, StyleSheet, TouchableOpacity, ScrollView } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useNavigation } from '@react-navigation/native';
import designTokens from '../styles/designTokens';

export default function TermsScreen() {
  const navigation = useNavigation();

  return (
    <SafeAreaView style={styles.container} edges={['top']}>
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity
          style={styles.backButton}
          onPress={() => navigation.goBack()}
          accessibilityLabel="Go back"
          accessibilityRole="button"
        >
          <Ionicons name="arrow-back" size={24} color={designTokens.colors.text.inverse} />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Terms & Conditions</Text>
        <View style={styles.headerRight} />
      </View>

      <ScrollView style={styles.content} showsVerticalScrollIndicator={false}>
        <Text style={styles.lastUpdated}>Last updated: March 2026</Text>

        <Text style={styles.sectionTitle}>1. Service Description</Text>
        <Text style={styles.body}>
          AskToddy is an AI-powered mobile application that generates construction cost estimates
          and quotes based on information you provide, including site assessments, photos, and
          project descriptions. The service is provided by AskToddy Ltd.
        </Text>

        <Text style={styles.sectionTitle}>2. Acceptance of Terms</Text>
        <Text style={styles.body}>
          By creating an account or using AskToddy, you agree to be bound by these Terms and
          Conditions. If you do not agree, please do not use the service.
        </Text>

        <Text style={styles.sectionTitle}>3. AI-Generated Quotes Disclaimer</Text>
        <Text style={styles.body}>
          All quotes and cost estimates generated by AskToddy are indicative estimates only and
          should not be treated as guaranteed prices. Estimates are generated by artificial
          intelligence based on the information you provide and publicly available pricing data.
          Actual costs may vary significantly depending on site conditions, material availability,
          labour rates, and other factors. AskToddy does not guarantee the accuracy, completeness,
          or reliability of any estimate.
        </Text>
        <Text style={styles.body}>
          You should always obtain formal quotes from qualified tradespeople before commencing any
          construction work. AskToddy is a planning and estimation tool — it is not a substitute for
          professional advice.
        </Text>

        <Text style={styles.sectionTitle}>4. Acceptable Use</Text>
        <Text style={styles.body}>
          You agree to use AskToddy only for lawful purposes. You must not:
        </Text>
        <Text style={styles.bullet}>
          • Use the service to generate fraudulent or misleading quotes.
        </Text>
        <Text style={styles.bullet}>
          • Attempt to reverse-engineer, decompile, or extract the AI models or algorithms.
        </Text>
        <Text style={styles.bullet}>• Upload harmful, illegal, or offensive content.</Text>
        <Text style={styles.bullet}>• Share your account credentials with others.</Text>
        <Text style={styles.bullet}>
          • Use automated tools to access the service beyond normal app usage.
        </Text>

        <Text style={styles.sectionTitle}>5. Account & Subscriptions</Text>
        <Text style={styles.body}>
          Free accounts include a limited number of AI-generated quotes per month. Premium
          subscriptions unlock additional features and higher usage limits. Subscriptions are
          managed through the Apple App Store or Google Play Store and are subject to their
          respective terms. You may cancel your subscription at any time through your device's
          subscription settings.
        </Text>

        <Text style={styles.sectionTitle}>6. Intellectual Property</Text>
        <Text style={styles.body}>
          The AskToddy app, including its design, branding, AI models, and source code, is the
          intellectual property of AskToddy Ltd. Quotes generated using the service are yours to use
          for personal or business purposes. You retain ownership of all content (photos, notes,
          data) you upload to the service.
        </Text>

        <Text style={styles.sectionTitle}>7. Limitation of Liability</Text>
        <Text style={styles.body}>
          To the fullest extent permitted by law, AskToddy Ltd shall not be liable for any indirect,
          incidental, special, consequential, or punitive damages arising from your use of the
          service. This includes, without limitation, any losses arising from reliance on
          AI-generated estimates, business interruption, or data loss.
        </Text>
        <Text style={styles.body}>
          Our total liability for any claim arising from the service shall not exceed the amount you
          have paid to us in the 12 months preceding the claim, or £100, whichever is greater.
        </Text>

        <Text style={styles.sectionTitle}>8. Account Termination</Text>
        <Text style={styles.body}>
          We reserve the right to suspend or terminate your account if you violate these terms or
          engage in behaviour that harms the service or other users. You may delete your account at
          any time by contacting support. Upon termination, your data will be handled in accordance
          with our Privacy Policy.
        </Text>

        <Text style={styles.sectionTitle}>9. Changes to Terms</Text>
        <Text style={styles.body}>
          We may update these Terms and Conditions from time to time. We will notify you of
          significant changes via the app or email. Continued use after changes constitutes
          acceptance.
        </Text>

        <Text style={styles.sectionTitle}>10. Governing Law</Text>
        <Text style={styles.body}>
          These Terms are governed by and construed in accordance with the laws of England and
          Wales. Any disputes arising from these Terms shall be subject to the exclusive
          jurisdiction of the courts of England and Wales.
        </Text>

        <Text style={styles.sectionTitle}>11. Contact Us</Text>
        <Text style={styles.body}>
          If you have questions about these Terms and Conditions, please contact us at:
        </Text>
        <Text style={styles.body}>Email: support@asktoddy.com</Text>

        <View style={styles.bottomSpacing} />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: designTokens.colors.navy[900],
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: designTokens.spacing.md,
    paddingVertical: designTokens.spacing.sm,
    backgroundColor: designTokens.colors.primary[500],
    borderBottomWidth: 1,
    borderBottomColor: designTokens.colors.primary[600],
  },
  backButton: {
    padding: designTokens.spacing.xs,
    borderRadius: designTokens.borderRadius.md,
  },
  headerTitle: {
    fontSize: designTokens.typography.fontSize.xl,
    fontWeight: designTokens.typography.fontWeight.bold as any,
    color: designTokens.colors.text.inverse,
  },
  headerRight: {
    width: 32,
  },
  content: {
    flex: 1,
    backgroundColor: designTokens.colors.background.primary,
    paddingHorizontal: designTokens.spacing.lg,
    paddingTop: designTokens.spacing.lg,
  },
  lastUpdated: {
    fontSize: designTokens.typography.fontSize.sm,
    color: designTokens.colors.text.tertiary,
    marginBottom: designTokens.spacing.lg,
    fontStyle: 'italic',
  },
  sectionTitle: {
    fontSize: designTokens.typography.fontSize.lg,
    fontWeight: designTokens.typography.fontWeight.semibold as any,
    color: designTokens.colors.text.primary,
    marginTop: designTokens.spacing.lg,
    marginBottom: designTokens.spacing.sm,
  },
  body: {
    fontSize: designTokens.typography.fontSize.base,
    color: designTokens.colors.text.secondary,
    lineHeight: 22,
    marginBottom: designTokens.spacing.sm,
  },
  bullet: {
    fontSize: designTokens.typography.fontSize.base,
    color: designTokens.colors.text.secondary,
    lineHeight: 22,
    marginBottom: designTokens.spacing.xs,
    paddingLeft: designTokens.spacing.md,
  },
  bottomSpacing: {
    height: 40,
  },
});
